name: Test an interface
# Checks the schema for the specified interface.

on:
  workflow_call:
    inputs:
      interface:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      interface:
        description: Name of interface to run checks for.
        required: true
        type: string

permissions: {}

env:
  INTERFACE: ${{ inputs.interface }}

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      - name: Find schema path
        id: schema
        run: |
          set -xueo pipefail
          SCHEMA=$(.scripts/ls.py interfaces --regex "interfaces/$INTERFACE" --output-only schema_path --no-json)
          echo "result=$SCHEMA" >> "$GITHUB_OUTPUT"
      - name: Check schema can be run if it exists
        if: steps.schema.outputs.result
        run: uv run --no-project --with-requirements schema-requirements.txt "$SCHEMA"
        env:
          SCHEMA: ${{ steps.schema.outputs.result }}
