name: Test a package
# runs tests for specified package
# always runs static tests
# runs unit, functional, and integration tests if the package implements them

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      skip-juju:
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      package:
        description: Package (by path) to run tests for.
        required: true
        type: string
      skip-juju:
        description: Skip Juju integration tests.
        required: false
        type: boolean

permissions: {}

env:
  PACKAGE: ${{ inputs.package }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      package-name: ${{ steps.package-info.outputs.name }}
      tests: ${{ steps.tests.outputs.tests }}
      python: ${{ steps.python.outputs.versions }}
      min_python_version: ${{ steps.python.outputs.min_version }}
      functional-matrix: ${{ steps.functional.outputs.matrix }}
      integration-substrates: ${{ steps.integration-substrates.outputs.substrates }}
      integration-tags: ${{ steps.integration-tags.outputs.tags }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

      - name: Ensure package uv.lock is up-to-date
        working-directory: ${{ inputs.package }}
        run: |
          case "$PWD" in
            */.example|*/.example/testing|*/.tutorial) echo "Examples don't have a uv.lock file, skipping ..." ;;
            *) uv lock --check ;;
          esac

      - name: Get package info
        id: package-info
        run: |
          set -xueo pipefail
          NAME=$(.scripts/ls.py packages --no-json --exclude-testing --output-only name --regex "$PACKAGE")
          echo "name=$NAME"
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Check which Python versions this package supports
        id: python
        run: uv run --no-project --script .github/get-supported-python-versions.py "$PACKAGE"

      - name: Check which test suites this package has
        id: tests
        run: |
          tests=()
          for test in unit functional integration; do
            if [ -d "$PACKAGE/tests/$test" ]; then
              tests+=($test)
            fi
          done
          js=$(jq '$ARGS.positional' --null-input --compact-output --args "${tests[@]}")
          echo "tests=$js"
          echo "tests=$js" >> "$GITHUB_OUTPUT"

      - name: Check requirements for functional tests
        id: functional
        if: contains(fromJson(steps.tests.outputs.tests), 'functional')
        run: uv run --no-project --script .github/get-functional-test-matrix.py "$PACKAGE"

      - name: Check substrates needed for integration tests
        id: integration-substrates
        if: contains(fromJson(steps.tests.outputs.tests), 'integration')
        env:
          PACKAGE: ${{ inputs.package }}
          PYTHON: ${{ steps.python.outputs.min_version }}
        run: |
          set -x  # print lines before executing them
          substrates=()
          for substrate in k8s machine; do
            set +e  # don't abort if the next process has a non-zero exit code
            uvx --from rust-just just integration-$substrate --python "$PYTHON" "$PACKAGE" --collect-only -q
            case $? in
                0) substrates+=($substrate);;
                5) echo "No tests for $substrate";;
                *) echo "Unexpected exit code $?"; exit 1;;
            esac
            set -e  # return to aborting if processes fail
          done
          js=$(jq '$ARGS.positional' --null-input --compact-output --args "${substrates[@]}")
          echo "substrates=$js"
          echo "substrates=$js" >> "$GITHUB_OUTPUT"

      - name: Check tags to run integration tests with
        id: integration-tags
        if: contains(fromJson(steps.tests.outputs.tests), 'integration')
        shell: python
        run: |
          import json, os, pathlib, tomllib
          pyproject_toml = tomllib.loads(pathlib.Path(os.environ['PACKAGE'], 'pyproject.toml').read_text())
          tags = pyproject_toml.get('tool', {}).get('charmlibs', {}).get('integration', {}).get('tags') or ['']
          line = f'tags={json.dumps(tags)}'
          print(line)
          with pathlib.Path(os.environ['GITHUB_OUTPUT']).open('a') as f:
            print(line, file=f)


  lint:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ${{ fromJson(needs.init.outputs.python) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

      - name: Run static analysis and other checks
        env:
          PYTHON: ${{ matrix.python }}
        run: uvx --from rust-just just lint --python "$PYTHON" "$PACKAGE"

  unit:
    needs: init
    if: contains(fromJson(needs.init.outputs.tests), 'unit')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ${{ fromJson(needs.init.outputs.python) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

      - name: Run unit tests
        env:
          PYTHON: ${{ matrix.python }}
        run: uvx --from rust-just just unit --python "$PYTHON" "$PACKAGE"

  functional:
    needs: init
    if: contains(fromJson(needs.init.outputs.tests), 'functional')
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.init.outputs.functional-matrix) }}
    runs-on: ${{ matrix.ubuntu }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version: '1.24'
          # To suppress the "Restore cache failed" error, since there is no go.sum file here.
          cache: false

      - name: Install Pebble
        if: matrix.pebble != 'no-pebble'
        env:
          PEBBLE: ${{ matrix.pebble }}
          GOTOOLCHAIN: auto
        run: go install "github.com/canonical/pebble/cmd/$PEBBLE"

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

      - name: Run functional tests
        if: matrix.sudo == 'no-sudo'
        run: uvx --from rust-just just functional --python python3 "$PACKAGE"

      - name: Run functional tests with sudo
        if: matrix.sudo != 'no-sudo'
        run: sudo env "PATH=$PATH" uvx --from rust-just just functional --python python3 "$PACKAGE"

  integration:
    needs: init
    if: contains(fromJson(needs.init.outputs.tests), 'integration') && !inputs.skip-juju
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJson(needs.init.outputs.integration-tags) }}
        substrate: ${{ fromJson(needs.init.outputs.integration-substrates) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: Install concierge
        run: sudo snap install --classic concierge

      - name: Prepare Juju for microk8s
        if: ${{ matrix.substrate == 'k8s' }}
        run: sudo concierge prepare --verbose --juju-channel=3/stable -p microk8s

      - name: Prepare Juju for machine
        if: ${{ matrix.substrate == 'machine' }}
        run: sudo concierge prepare --verbose --juju-channel=3/stable -p machine

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1

      - name: Pack charms
        if: ${{ hashFiles(format('{0}/tests/integration/pack.sh', inputs.package)) != '' }}
        id: pack
        env:
          TAG: ${{ matrix.tag }}
          SUBSTRATE: ${{ matrix.substrate }}
        run: uvx --from rust-just just "pack-$SUBSTRATE" --tag "$TAG" "$PACKAGE"

      - name: Run Juju integration tests
        id: integration
        env:
          PYTHON: ${{ needs.init.outputs.min_python_version }}
          RECIPE: integration-${{ matrix.substrate }}
          TAG: ${{ matrix.tag }}
        run: uvx --from rust-just just "$RECIPE" --python "$PYTHON" --tag "$TAG" "$PACKAGE"

      - name: Upload Charmcraft logs
        if: ${{ !cancelled() && (steps.pack.conclusion != 'skipped' || steps.integration.conclusion != 'skipped') }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: ${{ needs.init.outputs.package-name }}-charmcraft-logs-${{ matrix.substrate }}-${{ matrix.tag }}
          path: /home/runner/.local/state/charmcraft/log/charmcraft-*.log
          if-no-files-found: warn  # pack.sh scripts aren't required to produce charmcraft logs (though they do currently)
